{
  "metrics": {
    "risk_level": {
      "name": "Risk Level",
      "description": "Probability of failure or significant underperformance",
      "low_label": "Low Risk",
      "high_label": "High Risk",
      "rubric": {
        "1": "Nearly guaranteed returns (tenured government position)",
        "3": "Low risk (established medical specialty)",
        "5": "Moderate risk (established corporate career path)",
        "7": "High risk (well-funded startup with product-market fit)",
        "10": "Extreme risk (pre-seed startup in emerging market)"
      }
    },
    "capital_requirements": {
      "name": "Capital Requirements",
      "description": "Initial and ongoing investment needed",
      "low_label": "Minimal Capital",
      "high_label": "Major Investment",
      "rubric": {
        "1": "No investment (<$1,000)",
        "3": "Low investment ($1K-$10K)",
        "5": "Moderate investment ($10K-$50K)",
        "7": "Substantial investment ($50K-$200K)",
        "10": "Major investment (>$200K)"
      }
    },
    "technical_specialization": {
      "name": "Technical Specialization",
      "description": "Depth of technical expertise required",
      "low_label": "Generalist",
      "high_label": "Deep Specialist",
      "rubric": {
        "1": "General skills (basic business/communications)",
        "3": "Moderately specialized (MBA-level business knowledge)",
        "5": "Specialized (software engineering)",
        "7": "Highly specialized (machine learning engineering)",
        "10": "Extremely specialized (quantum computing research)"
      }
    },
    "network_dependency": {
      "name": "Network Dependency",
      "description": "Reliance on professional connections",
      "low_label": "Independent",
      "high_label": "Network Critical",
      "rubric": {
        "1": "Minimal networking required",
        "3": "Some networking helpful but not required",
        "5": "Networking important for advancement",
        "7": "Strong network required for key opportunities",
        "10": "Elite network essential for success"
      }
    },
    "scalability": {
      "name": "Scalability",
      "description": "How returns scale with effort/time",
      "low_label": "Linear Growth",
      "high_label": "Exponential Growth",
      "rubric": {
        "1": "Strictly limited by time (hourly consulting)",
        "3": "Limited scaling (small practice growth)",
        "5": "Moderate scaling (local business expansion)",
        "7": "Strong scaling (tech product with marginal costs)",
        "10": "Exponential scaling (platform business model)"
      }
    },
    "control": {
      "name": "Control/Agency",
      "description": "Degree of personal control over outcome",
      "low_label": "Limited Control",
      "high_label": "Full Control",
      "rubric": {
        "1": "Minimal control (entry-level employee)",
        "3": "Limited control (mid-level manager)",
        "5": "Moderate control (senior executive)",
        "7": "High control (minority founder)",
        "10": "Maximum control (majority founder/owner)"
      }
    },
    "geographic_dependency": {
      "name": "Geographic Dependency",
      "description": "Importance of specific location",
      "low_label": "Location Independent",
      "high_label": "Location Critical",
      "rubric": {
        "1": "Location-independent",
        "3": "Requires presence in any major metro area",
        "5": "Requires specific type of location (any tech hub)",
        "7": "Requires specific metro area (e.g., Silicon Valley)",
        "10": "Requires specific location within metro (e.g., Sand Hill Road)"
      }
    },
    "skill_transfer": {
      "name": "Skill Transferability",
      "description": "How skills developed transfer to other opportunities",
      "low_label": "Non-transferable",
      "high_label": "Highly Transferable",
      "rubric": {
        "1": "Skills have very limited application outside path",
        "3": "Skills transfer to closely related fields only",
        "5": "Skills partially transfer to several fields",
        "7": "Skills highly transferable across many domains",
        "10": "Skills universally valuable across industries"
      }
    },
    "time_to_return": {
      "name": "Time to Return",
      "description": "Years until significant returns begin",
      "low_label": "Quick Returns",
      "high_label": "Long-term Returns",
      "rubric": {
        "1": "Immediate returns (<1 year)",
        "3": "Short-term returns (1-2 years)",
        "5": "Medium-term returns (3-5 years)",
        "7": "Long-term returns (5-10 years)",
        "10": "Very long-term returns (10+ years)"
      }
    },
    "success_probability": {
      "name": "Probability of $10M Success",
      "description": "Likelihood of achieving $10M in 5 years",
      "low_label": "Very Unlikely",
      "high_label": "Relatively Likely",
      "rubric": {
        "1": "Extremely unlikely (<0.1%)",
        "3": "Very unlikely (0.1-1%)",
        "5": "Unlikely (1-5%)",
        "7": "Possible (5-15%)",
        "10": "Relatively likely (>15%)"
      }
    },
    "optionality": {
      "name": "Optionality Preservation",
      "description": "Ability to pivot to other opportunities",
      "low_label": "Few Options",
      "high_label": "Many Options",
      "rubric": {
        "1": "Extremely limiting (no future options)",
        "3": "Highly limiting (few future options)",
        "5": "Moderately limiting (some future options)",
        "7": "Minimally limiting (many future options)",
        "10": "Maximally preserving (all future options)"
      }
    },
    "terminal_value": {
      "name": "Terminal Value Potential",
      "description": "Maximum realistic outcome",
      "low_label": "Limited Ceiling",
      "high_label": "Unlimited Ceiling",
      "rubric": {
        "1": "Limited ceiling (<$1M)",
        "3": "Moderate ceiling ($1M-$5M)",
        "5": "Good ceiling ($5M-$25M)",
        "7": "High ceiling ($25M-$100M)",
        "10": "Unlimited ceiling (>$100M)"
      }
    },
    "expected_value_10yr": {
      "name": "10-Year Expected Value",
      "description": "Probability-adjusted outcome at 10 years",
      "low_label": "Low EV",
      "high_label": "High EV",
      "rubric": {
        "1": "Very low (<$100K)",
        "3": "Low ($100K-$500K)",
        "5": "Moderate ($500K-$2M)",
        "7": "High ($2M-$10M)",
        "10": "Very high (>$10M)"
      }
    },
    "competition": {
      "name": "Competitive Saturation",
      "description": "Level of competition in the space",
      "low_label": "Blue Ocean",
      "high_label": "Red Ocean",
      "rubric": {
        "1": "Blue ocean (virtually no competition)",
        "3": "Early emerging market (few competitors)",
        "5": "Growing market (moderate competition)",
        "7": "Mature market (strong competition)",
        "10": "Oversaturated market (extreme competition)"
      }
    },
    "social_impact": {
      "name": "Social Impact Potential",
      "description": "Capacity to create positive societal change",
      "low_label": "Minimal Impact",
      "high_label": "Transformative Impact",
      "rubric": {
        "1": "Minimal societal impact",
        "3": "Limited positive impact on small groups",
        "5": "Moderate impact on specific communities",
        "7": "Significant impact on large populations",
        "10": "Transformative global impact potential"
      }
    },
    "reversibility": {
      "name": "Decision Reversibility",
      "description": "Ability to change course if not working",
      "low_label": "Irreversible",
      "high_label": "Easily Reversed",
      "rubric": {
        "1": "Irreversible commitment (e.g., medical residency)",
        "3": "Major costs to reverse (e.g., law school)",
        "5": "Moderate costs to reverse (e.g., relocation)",
        "7": "Minor costs to reverse (e.g., changing jobs)",
        "10": "Fully reversible with minimal cost"
      }
    },
    "team_dependency": {
      "name": "Team Dependency",
      "description": "Reliance on others for success",
      "low_label": "Solo Endeavor",
      "high_label": "Large Team Required",
      "rubric": {
        "1": "Pure solo endeavor (independent creator)",
        "3": "Small team (2-5 people)",
        "5": "Medium team (5-20 people)",
        "7": "Large team (20-100 people)",
        "10": "Massive team (100+ people)"
      }
    },
    "regulatory_barriers": {
      "name": "Regulatory Barriers",
      "description": "Level of regulatory hurdles",
      "low_label": "Unregulated",
      "high_label": "Heavily Regulated",
      "rubric": {
        "1": "Virtually unregulated field",
        "3": "Light regulation (standard business rules)",
        "5": "Moderate regulation (industry-specific rules)",
        "7": "Heavy regulation (strict compliance needs)",
        "10": "Extremely regulated (FDA approval, etc.)"
      }
    },
    "knowledge_half_life": {
      "name": "Knowledge Half-Life",
      "description": "How quickly core knowledge becomes outdated",
      "low_label": "Rapidly Changing",
      "high_label": "Enduring Knowledge",
      "rubric": {
        "1": "Very short half-life (<1 year, e.g., specific ML frameworks)",
        "3": "Short half-life (1-3 years, e.g., web technologies)",
        "5": "Medium half-life (3-7 years, e.g., programming languages)",
        "7": "Long half-life (7-15 years, e.g., core CS principles)",
        "10": "Very long half-life (>15 years, e.g., mathematics)"
      }
    }
  },
  "categories": [
    "Tech & Software",
    "Materials & Energy",
    "Education",
    "3D & Manufacturing",
    "Content & Media",
    "Finance & Investment",
    "Traditional Professions",
    "Retail & Consumer",
    "Health & Wellness"
  ],
  "pathways": [
    {
      "id": "ai_materials_startup_founder",
      "name": "AI Materials Discovery Startup Founder",
      "category": "Materials & Energy",
      "description": "Found a company applying AI to discover novel materials for batteries, solar, or superconductors",
      "target_customers": "Research institutions, energy companies, and manufacturing firms",
      "success_examples": ["Citrine Informatics", "Materials Zone", "Orbital Materials"],
      "key_skills": ["Materials Science", "Machine Learning", "Chemistry", "Software Development", "Business Development"],
      "metrics": {
        "risk_level": {"value": 7, "range": [6, 8]},
        "capital_requirements": {"value": 7, "range": [6, 8]},
        "technical_specialization": {"value": 9, "range": [8, 10]},
        "network_dependency": {"value": 8, "range": [7, 9]},
        "scalability": {"value": 8, "range": [7, 9]},
        "control": {"value": 9, "range": [8, 10]},
        "geographic_dependency": {"value": 5, "range": [4, 6]},
        "skill_transfer": {"value": 7, "range": [6, 8]},
        "time_to_return": {"value": 6, "range": [5, 7]},
        "success_probability": {"value": 5, "range": [4, 6]},
        "optionality": {"value": 6, "range": [5, 7]},
        "terminal_value": {"value": 9, "range": [8, 10]},
        "expected_value_10yr": {"value": 7, "range": [6, 8]},
        "competition": {"value": 5, "range": [4, 6]},
        "social_impact": {"value": 8, "range": [7, 9]},
        "reversibility": {"value": 5, "range": [4, 6]},
        "team_dependency": {"value": 7, "range": [6, 8]},
        "regulatory_barriers": {"value": 4, "range": [3, 5]},
        "knowledge_half_life": {"value": 5, "range": [4, 6]}
      },
      "rationale": {
        "risk_level": "High risk (7/10) based on ~90% AI startup failure rate, but mitigated by clear industrial applications",
        "capital_requirements": "Substantial investment (7/10) needed for R&D, specialized staff, computing resources",
        "technical_specialization": "Extremely specialized (9/10) requiring rare combination of materials science and AI expertise",
        "success_probability": "Unlikely but possible (5/10) with 1-5% chance of reaching $10M given observed exits in the space",
        "terminal_value": "Very high ceiling (9/10) with potential exits of $100M-$3B based on recent valuations"
      }
    },
    {
      "id": "quantitative_trading_principal",
      "name": "Quantitative Trading/Research Principal",
      "category": "Finance & Investment",
      "description": "Develop and implement algorithmic trading strategies at elite firms",
      "target_customers": "Hedge funds, proprietary trading firms, asset managers",
      "success_examples": ["Renaissance Technologies", "Two Sigma", "Citadel"],
      "key_skills": ["Advanced Mathematics", "Machine Learning", "Programming", "Financial Markets"],
      "metrics": {
        "risk_level": {"value": 3, "range": [2, 4]},
        "capital_requirements": {"value": 2, "range": [1, 3]},
        "technical_specialization": {"value": 10, "range": [9, 10]},
        "network_dependency": {"value": 5, "range": [4, 6]},
        "scalability": {"value": 9, "range": [8, 10]},
        "control": {"value": 5, "range": [4, 6]},
        "geographic_dependency": {"value": 6, "range": [5, 7]},
        "skill_transfer": {"value": 8, "range": [7, 9]},
        "time_to_return": {"value": 5, "range": [4, 6]},
        "success_probability": {"value": 6, "range": [5, 7]},
        "optionality": {"value": 7, "range": [6, 8]},
        "terminal_value": {"value": 8, "range": [7, 9]},
        "expected_value_10yr": {"value": 8, "range": [7, 9]},
        "competition": {"value": 9, "range": [8, 10]},
        "social_impact": {"value": 3, "range": [2, 4]},
        "reversibility": {"value": 8, "range": [7, 9]},
        "team_dependency": {"value": 7, "range": [6, 8]},
        "regulatory_barriers": {"value": 4, "range": [3, 5]},
        "knowledge_half_life": {"value": 6, "range": [5, 7]}
      },
      "rationale": {
        "risk_level": "Low risk (3/10) as an employment path compared to entrepreneurial options",
        "technical_specialization": "Extremely specialized (10/10) requiring advanced mathematical and programming skills",
        "success_probability": "Above average (6/10) with top quants earning $1-10M+ annually at elite firms",
        "competition": "Extremely competitive (9/10) with global talent pool competing for limited positions"
      }
    },
    {
      "id": "family_office_medicine",
      "name": "Family Office-Style Concierge Medicine Practice",
      "category": "Health & Wellness",
      "description": "Create an ultra-premium medical practice serving high-net-worth clients",
      "target_customers": "Ultra-high-net-worth individuals and families",
      "success_examples": ["MD²", "Private Medical", "WorldClinic"],
      "key_skills": ["Medical Expertise", "Business Development", "Luxury Service", "Network Building"],
      "metrics": {
        "risk_level": {"value": 4, "range": [3, 5]},
        "capital_requirements": {"value": 5, "range": [4, 6]},
        "technical_specialization": {"value": 8, "range": [7, 9]},
        "network_dependency": {"value": 10, "range": [9, 10]},
        "scalability": {"value": 5, "range": [4, 6]},
        "control": {"value": 9, "range": [8, 10]},
        "geographic_dependency": {"value": 9, "range": [8, 10]},
        "skill_transfer": {"value": 5, "range": [4, 6]},
        "time_to_return": {"value": 4, "range": [3, 5]},
        "success_probability": {"value": 7, "range": [6, 8]},
        "optionality": {"value": 4, "range": [3, 5]},
        "terminal_value": {"value": 7, "range": [6, 8]},
        "expected_value_10yr": {"value": 8, "range": [7, 9]},
        "competition": {"value": 6, "range": [5, 7]},
        "social_impact": {"value": 4, "range": [3, 5]},
        "reversibility": {"value": 6, "range": [5, 7]},
        "team_dependency": {"value": 5, "range": [4, 6]},
        "regulatory_barriers": {"value": 8, "range": [7, 9]},
        "knowledge_half_life": {"value": 7, "range": [6, 8]}
      },
      "rationale": {
        "risk_level": "Moderate risk (4/10) due to high barriers to entry but steady demand",
        "network_dependency": "Extremely high dependency (10/10) as access to wealthy clients is essential",
        "geographic_dependency": "Very high dependency (9/10) requiring presence in ultra-wealthy areas",
        "success_probability": "High probability (7/10) with membership fees of $25K-$100K per patient allowing $10M accumulation in 5-7 years"
      }
    },
    {
      "id": "ai_manufacturing_founder",
      "name": "AI Manufacturability Analysis Startup Founder",
      "category": "3D & Manufacturing",
      "description": "Create AI systems for defect prediction, optimization, and quality control in manufacturing",
      "target_customers": "Manufacturing companies, industrial equipment makers, precision manufacturers",
      "success_examples": ["Instrumental", "Landing AI", "Veo Robotics"],
      "key_skills": ["Machine Learning", "Computer Vision", "Manufacturing Processes", "Software Development"],
      "metrics": {
        "risk_level": {"value": 6, "range": [5, 7]},
        "capital_requirements": {"value": 6, "range": [5, 7]},
        "technical_specialization": {"value": 8, "range": [7, 9]},
        "network_dependency": {"value": 7, "range": [6, 8]},
        "scalability": {"value": 8, "range": [7, 9]},
        "control": {"value": 9, "range": [8, 10]},
        "geographic_dependency": {"value": 4, "range": [3, 5]},
        "skill_transfer": {"value": 7, "range": [6, 8]},
        "time_to_return": {"value": 5, "range": [4, 6]},
        "success_probability": {"value": 6, "range": [5, 7]},
        "optionality": {"value": 7, "range": [6, 8]},
        "terminal_value": {"value": 8, "range": [7, 9]},
        "expected_value_10yr": {"value": 8, "range": [7, 9]},
        "competition": {"value": 6, "range": [5, 7]},
        "social_impact": {"value": 7, "range": [6, 8]},
        "reversibility": {"value": 6, "range": [5, 7]},
        "team_dependency": {"value": 6, "range": [5, 7]},
        "regulatory_barriers": {"value": 3, "range": [2, 4]},
        "knowledge_half_life": {"value": 6, "range": [5, 7]}
      },
      "rationale": {
        "risk_level": "Moderately high risk (6/10) but with clear ROI for manufacturing clients",
        "success_probability": "Above average (6/10) as manufacturing AI companies show 30-50% higher success rates than general AI startups",
        "terminal_value": "High ceiling (8/10) with potential exits of $30-500M as acquisition targets for industrial tech companies",
        "expected_value_10yr": "High expected value (8/10) due to clear industrial applications and demonstrated ROI"
      }
    },
    {
      "id": "ai_education_platform",
      "name": "AI Education Platform Founder",
      "category": "Education",
      "description": "Develop an adaptive AI learning system that personalizes education",
      "target_customers": "K-12 schools, universities, corporate training departments",
      "success_examples": ["Khan Academy", "Duolingo", "Coursera"],
      "key_skills": ["Machine Learning", "Education Design", "Software Development", "UX Design"],
      "metrics": {
        "risk_level": {"value": 7, "range": [6, 8]},
        "capital_requirements": {"value": 6, "range": [5, 7]},
        "technical_specialization": {"value": 7, "range": [6, 8]},
        "network_dependency": {"value": 6, "range": [5, 7]},
        "scalability": {"value": 9, "range": [8, 10]},
        "control": {"value": 8, "range": [7, 9]},
        "geographic_dependency": {"value": 3, "range": [2, 4]},
        "skill_transfer": {"value": 8, "range": [7, 9]},
        "time_to_return": {"value": 6, "range": [5, 7]},
        "success_probability": {"value": 4, "range": [3, 5]},
        "optionality": {"value": 7, "range": [6, 8]},
        "terminal_value": {"value": 9, "range": [8, 10]},
        "expected_value_10yr": {"value": 7, "range": [6, 8]},
        "competition": {"value": 8, "range": [7, 9]},
        "social_impact": {"value": 9, "range": [8, 10]},
        "reversibility": {"value": 6, "range": [5, 7]},
        "team_dependency": {"value": 7, "range": [6, 8]},
        "regulatory_barriers": {"value": 5, "range": [4, 6]},
        "knowledge_half_life": {"value": 4, "range": [3, 5]}
      },
      "rationale": {
        "risk_level": "High risk (7/10) with 88-92% edtech failure rate but growing demand",
        "scalability": "Extremely scalable (9/10) as software can serve unlimited students with marginal costs",
        "competition": "Highly competitive (8/10) with many well-funded players and established institutions",
        "social_impact": "Very high impact potential (9/10) with ability to transform educational outcomes globally"
      }
    },
    {
      "id": "plastic_surgery_medspa",
      "name": "Private Practice Plastic Surgery with Medical Spa Integration",
      "category": "Health & Wellness",
      "description": "Develop a specialized surgical practice with integrated medical aesthetics services",
      "target_customers": "Affluent individuals seeking cosmetic procedures and treatments",
      "success_examples": ["Beverly Hills Plastic Surgery Group", "Manhattan Aesthetics"],
      "key_skills": ["Surgical Expertise", "Business Management", "Team Leadership", "Marketing"],
      "metrics": {
        "risk_level": {"value": 4, "range": [3, 5]},
        "capital_requirements": {"value": 8, "range": [7, 9]},
        "technical_specialization": {"value": 9, "range": [8, 10]},
        "network_dependency": {"value": 8, "range": [7, 9]},
        "scalability": {"value": 6, "range": [5, 7]},
        "control": {"value": 9, "range": [8, 10]},
        "geographic_dependency": {"value": 8, "range": [7, 9]},
        "skill_transfer": {"value": 5, "range": [4, 6]},
        "time_to_return": {"value": 7, "range": [6, 8]},
        "success_probability": {"value": 7, "range": [6, 8]},
        "optionality": {"value": 4, "range": [3, 5]},
        "terminal_value": {"value": 8, "range": [7, 9]},
        "expected_value_10yr": {"value": 7, "range": [6, 8]},
        "competition": {"value": 7, "range": [6, 8]},
        "social_impact": {"value": 5, "range": [4, 6]},
        "reversibility": {"value": 4, "range": [3, 5]},
        "team_dependency": {"value": 7, "range": [6, 8]},
        "regulatory_barriers": {"value": 8, "range": [7, 9]},
        "knowledge_half_life": {"value": 6, "range": [5, 7]}
      },
      "rationale": {
        "risk_level": "Moderate risk (4/10) with high success rates compared to many entrepreneurial ventures",
        "capital_requirements": "High capital needs (8/10) for facility, equipment, and training",
        "success_probability": "High probability (7/10) with established practice models and consistent demand",
        "time_to_return": "Long investment horizon (7/10) including training period but steady returns thereafter"
      }
    },
    {
      "id": "private_equity_partner",
      "name": "Private Equity Partner/Managing Director",
      "category": "Finance & Investment",
      "description": "Rise to partner level at established private equity firm",
      "target_customers": "Institutional investors, pension funds, sovereign wealth funds",
      "success_examples": ["Blackstone", "KKR", "Apollo"],
      "key_skills": ["Financial Analysis", "Deal Structuring", "Relationship Building", "Industry Expertise"],
      "metrics": {
        "risk_level": {"value": 4, "range": [3, 5]},
        "capital_requirements": {"value": 3, "range": [2, 4]},
        "technical_specialization": {"value": 7, "range": [6, 8]},
        "network_dependency": {"value": 9, "range": [8, 10]},
        "scalability": {"value": 7, "range": [6, 8]},
        "control": {"value": 6, "range": [5, 7]},
        "geographic_dependency": {"value": 7, "range": [6, 8]},
        "skill_transfer": {"value": 7, "range": [6, 8]},
        "time_to_return": {"value": 7, "range": [6, 8]},
        "success_probability": {"value": 6, "range": [5, 7]},
        "optionality": {"value": 6, "range": [5, 7]},
        "terminal_value": {"value": 8, "range": [7, 9]},
        "expected_value_10yr": {"value": 8, "range": [7, 9]},
        "competition": {"value": 9, "range": [8, 10]},
        "social_impact": {"value": 4, "range": [3, 5]},
        "reversibility": {"value": 7, "range": [6, 8]},
        "team_dependency": {"value": 8, "range": [7, 9]},
        "regulatory_barriers": {"value": 6, "range": [5, 7]},
        "knowledge_half_life": {"value": 7, "range": [6, 8]}
      },
      "rationale": {
        "risk_level": "Moderate risk (4/10) with established career path but competitive advancement",
        "network_dependency": "Very high dependency (9/10) requiring elite connections for deal flow",
        "success_probability": "Above average (6/10) with partners at $5B+ funds earning $500K-$900K base plus carried interest of $5-10M+ over fund cycles",
        "time_to_return": "Long term (7/10) typically requiring 7-10 years to reach partner level"
      }
    },
    {
      "id": "medical_specialist",
      "name": "Medical Specialist with Private Practice",
      "category": "Traditional Professions",
      "description": "Become specialized physician with own practice",
      "target_customers": "Patients with specific medical needs",
      "success_examples": ["Specialized surgeons", "Dermatologists with cosmetic focus"],
      "key_skills": ["Medical Expertise", "Business Management", "Patient Care", "Networking"],
      "metrics": {
        "risk_level": {"value": 3, "range": [2, 4]},
        "capital_requirements": {"value": 7, "range": [6, 8]},
        "technical_specialization": {"value": 10, "range": [9, 10]},
        "network_dependency": {"value": 6, "range": [5, 7]},
        "scalability": {"value": 3, "range": [2, 4]},
        "control": {"value": 8, "range": [7, 9]},
        "geographic_dependency": {"value": 6, "range": [5, 7]},
        "skill_transfer": {"value": 4, "range": [3, 5]},
        "time_to_return": {"value": 9, "range": [8, 10]},
        "success_probability": {"value": 6, "range": [5, 7]},
        "optionality": {"value": 3, "range": [2, 4]},
        "terminal_value": {"value": 7, "range": [6, 8]},
        "expected_value_10yr": {"value": 7, "range": [6, 8]},
        "competition": {"value": 6, "range": [5, 7]},
        "social_impact": {"value": 8, "range": [7, 9]},
        "reversibility": {"value": 2, "range": [1, 3]},
        "team_dependency": {"value": 4, "range": [3, 5]},
        "regulatory_barriers": {"value": 9, "range": [8, 10]},
        "knowledge_half_life": {"value": 7, "range": [6, 8]}
      },
      "rationale": {
        "risk_level": "Low risk (3/10) with established career path and steady demand",
        "time_to_return": "Very long term (9/10) requiring 8-14 years of education and training",
        "reversibility": "Very difficult to reverse (2/10) after significant educational investment",
        "success_probability": "Above average (6/10) with top specialists earning $500K-$1.5M+ annually"
      }
    },
    {
      "id": "tech_startup_early_employee",
      "name": "High-Growth Startup (Early Employee)",
      "category": "Tech & Software",
      "description": "Join pre-Series A startup with significant equity as early engineer or executive",
      "target_customers": "Varies by startup focus",
      "success_examples": ["Early employees at Stripe, Figma, Notion"],
      "key_skills": ["Software Development", "Product Development", "Growth Strategy", "Adaptability"],
      "metrics": {
        "risk_level": {"value": 6, "range": [5, 7]},
        "capital_requirements": {"value": 1, "range": [1, 2]},
        "technical_specialization": {"value": 7, "range": [6, 8]},
        "network_dependency": {"value": 7, "range": [6, 8]},
        "scalability": {"value": 6, "range": [5, 7]},
        "control": {"value": 4, "range": [3, 5]},
        "geographic_dependency": {"value": 6, "range": [5, 7]},
        "skill_transfer": {"value": 8, "range": [7, 9]},
        "time_to_return": {"value": 5, "range": [4, 6]},
        "success_probability": {"value": 4, "range": [3, 5]},
        "optionality": {"value": 7, "range": [6, 8]},
        "terminal_value": {"value": 8, "range": [7, 9]},
        "expected_value_10yr": {"value": 6, "range": [5, 7]},
        "competition": {"value": 8, "range": [7, 9]},
        "social_impact": {"value": 6, "range": [5, 7]},
        "reversibility": {"value": 8, "range": [7, 9]},
        "team_dependency": {"value": 8, "range": [7, 9]},
        "regulatory_barriers": {"value": 3, "range": [2, 4]},
        "knowledge_half_life": {"value": 5, "range": [4, 6]}
      },
      "rationale": {
        "risk_level": "Moderate risk (6/10) but less than founding your own venture",
        "success_probability": "Low to moderate (4/10) as only ~5% of startups achieve unicorn status needed for $10M outcome with typical early employee equity",
        "optionality": "High optionality (7/10) as early startup experience is highly valued",
        "terminal_value": "High ceiling (8/10) with potential for $5-50M with significant equity and successful exit"
      }
    },
    {
      "id": "serial_entrepreneur",
      "name": "Serial Entrepreneur",
      "category": "Tech & Software",
      "description": "Build and sell multiple companies in succession, reinvesting proceeds",
      "target_customers": "Varies by venture",
      "success_examples": ["Elon Musk", "Max Levchin", "Kevin Ryan"],
      "key_skills": ["Business Development", "Product Strategy", "Team Building", "Capital Raising"],
      "metrics": {
        "risk_level": {"value": 8, "range": [7, 9]},
        "capital_requirements": {"value": 5, "range": [4, 6]},
        "technical_specialization": {"value": 6, "range": [5, 7]},
        "network_dependency": {"value": 9, "range": [8, 10]},
        "scalability": {"value": 8, "range": [7, 9]},
        "control": {"value": 9, "range": [8, 10]},
        "geographic_dependency": {"value": 6, "range": [5, 7]},
        "skill_transfer": {"value": 9, "range": [8, 10]},
        "time_to_return": {"value": 4, "range": [3, 5]},
        "success_probability": {"value": 5, "range": [4, 6]},
        "optionality": {"value": 8, "range": [7, 9]},
        "terminal_value": {"value": 10, "range": [9, 10]},
        "expected_value_10yr": {"value": 8, "range": [7, 9]},
        "competition": {"value": 7, "range": [6, 8]},
        "social_impact": {"value": 7, "range": [6, 8]},
        "reversibility": {"value": 7, "range": [6, 8]},
        "team_dependency": {"value": 8, "range": [7, 9]},
        "regulatory_barriers": {"value": 4, "range": [3, 5]},
        "knowledge_half_life": {"value": 6, "range": [5, 7]}
      },
      "rationale": {
        "risk_level": "High risk (8/10) for each individual venture but diversified across multiple attempts",
        "success_probability": "Moderate (5/10) as experience increases success rates of subsequent ventures",
        "terminal_value": "Unlimited ceiling (10/10) with compounding returns from multiple successful exits",
        "skill_transfer": "Extremely high transferability (9/10) as entrepreneurial skills apply across ventures"
      }
    },
    {
      "id": "tech_executive",
      "name": "Technical Executive Path",
      "category": "Tech & Software",
      "description": "Rise to CTO/VP Engineering level at high-growth tech company",
      "target_customers": "N/A (internal leadership role)",
      "success_examples": ["CTOs at FAANG companies", "Engineering VPs at unicorns"],
      "key_skills": ["Technical Leadership", "Engineering Management", "Strategic Planning", "Communication"],
      "metrics": {
        "risk_level": {"value": 4, "range": [3, 5]},
        "capital_requirements": {"value": 1, "range": [1, 2]},
        "technical_specialization": {"value": 8, "range": [7, 9]},
        "network_dependency": {"value": 7, "range": [6, 8]},
        "scalability": {"value": 5, "range": [4, 6]},
        "control": {"value": 5, "range": [4, 6]},
        "geographic_dependency": {"value": 6, "range": [5, 7]},
        "skill_transfer": {"value": 7, "range": [6, 8]},
        "time_to_return": {"value": 6, "range": [5, 7]},
        "success_probability": {"value": 5, "range": [4, 6]},
        "optionality": {"value": 7, "range": [6, 8]},
        "terminal_value": {"value": 7, "range": [6, 8]},
        "expected_value_10yr": {"value": 6, "range": [5, 7]},
        "competition": {"value": 8, "range": [7, 9]},
        "social_impact": {"value": 5, "range": [4, 6]},
        "reversibility": {"value": 8, "range": [7, 9]},
        "team_dependency": {"value": 8, "range": [7, 9]},
        "regulatory_barriers": {"value": 2, "range": [1, 3]},
        "knowledge_half_life": {"value": 5, "range": [4, 6]}
      },
      "rationale": {
        "risk_level": "Moderate risk (4/10) with established career ladder",
        "technical_specialization": "High specialization (8/10) requiring deep technical expertise plus leadership",
        "success_probability": "Moderate (5/10) with total compensation packages at top firms reaching $1-3M annually",
        "time_to_return": "Medium-term (6/10) requiring 5-8 years to reach executive levels"
      }
    },
    {
      "id": "specialized_tech_consultant",
      "name": "Elite Technical Specialization",
      "category": "Tech & Software",
      "description": "Become recognized expert in high-value domain like AI security or cloud architecture",
      "target_customers": "Enterprise companies, tech firms, government agencies",
      "success_examples": ["Top independent security consultants", "Cloud architecture experts"],
      "key_skills": ["Deep Technical Expertise", "Problem Solving", "Communication", "Business Development"],
      "metrics": {
        "risk_level": {"value": 3, "range": [2, 4]},
        "capital_requirements": {"value": 2, "range": [1, 3]},
        "technical_specialization": {"value": 9, "range": [8, 10]},
        "network_dependency": {"value": 7, "range": [6, 8]},
        "scalability": {"value": 4, "range": [3, 5]},
        "control": {"value": 8, "range": [7, 9]},
        "geographic_dependency": {"value": 4, "range": [3, 5]},
        "skill_transfer": {"value": 6, "range": [5, 7]},
        "time_to_return": {"value": 5, "range": [4, 6]},
        "success_probability": {"value": 6, "range": [5, 7]},
        "optionality": {"value": 7, "range": [6, 8]},
        "terminal_value": {"value": 6, "range": [5, 7]},
        "expected_value_10yr": {"value": 6, "range": [5, 7]},
        "competition": {"value": 6, "range": [5, 7]},
        "social_impact": {"value": 5, "range": [4, 6]},
        "reversibility": {"value": 7, "range": [6, 8]},
        "team_dependency": {"value": 3, "range": [2, 4]},
        "regulatory_barriers": {"value": 3, "range": [2, 4]},
        "knowledge_half_life": {"value": 4, "range": [3, 5]}
      },
      "rationale": {
        "risk_level": "Low risk (3/10) with established demand for specialized expertise",
        "technical_specialization": "Very high specialization (9/10) requiring cutting-edge knowledge",
        "scalability": "Limited scalability (4/10) primarily constrained by personal time",
        "success_probability": "Above average (6/10) with top specialists earning $300-500/hr or $600K-1M+ annually"
      }
    },
    {
      "id": "tech_consulting_agency",
      "name": "Consulting/Agency Model",
      "category": "Tech & Software",
      "description": "Build boutique technical consultancy with specialized team and services",
      "target_customers": "Mid-market and enterprise businesses needing specialized expertise",
      "success_examples": ["Thoughtworks", "Pivotal Labs", "10up"],
      "key_skills": ["Technical Expertise", "Client Relationship Management", "Team Leadership", "Business Development"],
      "metrics": {
        "risk_level": {"value": 5, "range": [4, 6]},
        "capital_requirements": {"value": 3, "range": [2, 4]},
        "technical_specialization": {"value": 7, "range": [6, 8]},
        "network_dependency": {"value": 8, "range": [7, 9]},
        "scalability": {"value": 6, "range": [5, 7]},
        "control": {"value": 8, "range": [7, 9]},
        "geographic_dependency": {"value": 5, "range": [4, 6]},
        "skill_transfer": {"value": 7, "range": [6, 8]},
        "time_to_return": {"value": 4, "range": [3, 5]},
        "success_probability": {"value": 6, "range": [5, 7]},
        "optionality": {"value": 7, "range": [6, 8]},
        "terminal_value": {"value": 6, "range": [5, 7]},
        "expected_value_10yr": {"value": 6, "range": [5, 7]},
        "competition": {"value": 7, "range": [6, 8]},
        "social_impact": {"value": 5, "range": [4, 6]},
        "reversibility": {"value": 7, "range": [6, 8]},
        "team_dependency": {"value": 7, "range": [6, 8]},
        "regulatory_barriers": {"value": 2, "range": [1, 3]},
        "knowledge_half_life": {"value": 5, "range": [4, 6]}
      },
      "rationale": {
        "risk_level": "Moderate risk (5/10) with established business model",
        "network_dependency": "High dependency (8/10) as client relationships drive business",
        "time_to_return": "Relatively quick returns (4/10) with profitable operations possible within 1-2 years",
        "terminal_value": "Good ceiling (6/10) with boutique consultancies typically selling for 2-4x annual revenue"
      }
    },
    {
      "id": "investment_strategy",
      "name": "High-Income Tech Role + Angel Investing",
      "category": "Finance & Investment",
      "description": "Combine principal engineer/tech executive role with systematic angel investing",
      "target_customers": "Startups seeking early-stage funding",
      "success_examples": ["Tech executives with angel portfolios", "AngelList syndicates"],
      "key_skills": ["Technical Expertise", "Financial Analysis", "Network Building", "Portfolio Management"],
      "metrics": {
        "risk_level": {"value": 5, "range": [4, 6]},
        "capital_requirements": {"value": 6, "range": [5, 7]},
        "technical_specialization": {"value": 8, "range": [7, 9]},
        "network_dependency": {"value": 8, "range": [7, 9]},
        "scalability": {"value": 7, "range": [6, 8]},
        "control": {"value": 6, "range": [5, 7]},
        "geographic_dependency": {"value": 7, "range": [6, 8]},
        "skill_transfer": {"value": 8, "range": [7, 9]},
        "time_to_return": {"value": 7, "range": [6, 8]},
        "success_probability": {"value": 5, "range": [4, 6]},
        "optionality": {"value": 8, "range": [7, 9]},
        "terminal_value": {"value": 8, "range": [7, 9]},
        "expected_value_10yr": {"value": 7, "range": [6, 8]},
        "competition": {"value": 7, "range": [6, 8]},
        "social_impact": {"value": 6, "range": [5, 7]},
        "reversibility": {"value": 7, "range": [6, 8]},
        "team_dependency": {"value": 5, "range": [4, 6]},
        "regulatory_barriers": {"value": 4, "range": [3, 5]},
        "knowledge_half_life": {"value": 6, "range": [5, 7]}
      },
      "rationale": {
        "risk_level": "Moderate risk (5/10) combining stable employment with diversified investments",
        "capital_requirements": "Substantial (6/10) requiring $500K-$2M in investment capital over time",
        "success_probability": "Moderate (5/10) depending on portfolio performance and access to deals",
        "optionality": "High optionality (8/10) maintaining professional career while building investment portfolio"
      }
    },
    {
      "id": "saas_product_founder",
      "name": "Software Product Development",
      "category": "Tech & Software",
      "description": "Create bootstrapped software product with recurring revenue",
      "target_customers": "Businesses or consumers with specific needs",
      "success_examples": ["Basecamp", "Mailchimp", "Ahrefs"],
      "key_skills": ["Software Development", "Product Design", "Marketing", "Customer Support"],
      "metrics": {
        "risk_level": {"value": 5, "range": [4, 6]},
        "capital_requirements": {"value": 3, "range": [2, 4]},
        "technical_specialization": {"value": 7, "range": [6, 8]},
        "network_dependency": {"value": 5, "range": [4, 6]},
        "scalability": {"value": 8, "range": [7, 9]},
        "control": {"value": 9, "range": [8, 10]},
        "geographic_dependency": {"value": 3, "range": [2, 4]},
        "skill_transfer": {"value": 7, "range": [6, 8]},
        "time_to_return": {"value": 4, "range": [3, 5]},
        "success_probability": {"value": 5, "range": [4, 6]},
        "optionality": {"value": 7, "range": [6, 8]},
        "terminal_value": {"value": 8, "range": [7, 9]},
        "expected_value_10yr": {"value": 7, "range": [6, 8]},
        "competition": {"value": 7, "range": [6, 8]},
        "social_impact": {"value": 6, "range": [5, 7]},
        "reversibility": {"value": 7, "range": [6, 8]},
        "team_dependency": {"value": 4, "range": [3, 5]},
        "regulatory_barriers": {"value": 3, "range": [2, 4]},
        "knowledge_half_life": {"value": 5, "range": [4, 6]}
      },
      "rationale": {
        "risk_level": "Moderate risk (5/10) with self-funded approach reducing financial exposure",
        "control": "Very high control (9/10) through bootstrapped funding and ownership",
        "scalability": "Strong scalability (8/10) with software's marginal cost advantages",
        "geographic_dependency": "Low dependency (3/10) allowing remote or distributed operations"
      }
    },
    {
      "id": "real_estate_development",
      "name": "Real Estate Development",
      "category": "Finance & Investment",
      "description": "Leverage technical expertise for property development and improvement",
      "target_customers": "Property buyers, renters, or commercial tenants",
      "success_examples": ["Small-scale developers", "Engineering-focused property tech firms"],
      "key_skills": ["Construction/Engineering Knowledge", "Financial Analysis", "Project Management", "Market Analysis"],
      "metrics": {
        "risk_level": {"value": 6, "range": [5, 7]},
        "capital_requirements": {"value": 8, "range": [7, 9]},
        "technical_specialization": {"value": 6, "range": [5, 7]},
        "network_dependency": {"value": 7, "range": [6, 8]},
        "scalability": {"value": 6, "range": [5, 7]},
        "control": {"value": 8, "range": [7, 9]},
        "geographic_dependency": {"value": 8, "range": [7, 9]},
        "skill_transfer": {"value": 6, "range": [5, 7]},
        "time_to_return": {"value": 6, "range": [5, 7]},
        "success_probability": {"value": 6, "range": [5, 7]},
        "optionality": {"value": 5, "range": [4, 6]},
        "terminal_value": {"value": 8, "range": [7, 9]},
        "expected_value_10yr": {"value": 7, "range": [6, 8]},
        "competition": {"value": 7, "range": [6, 8]},
        "social_impact": {"value": 6, "range": [5, 7]},
        "reversibility": {"value": 5, "range": [4, 6]},
        "team_dependency": {"value": 7, "range": [6, 8]},
        "regulatory_barriers": {"value": 7, "range": [6, 8]},
        "knowledge_half_life": {"value": 8, "range": [7, 9]}
      },
      "rationale": {
        "risk_level": "Moderate to high risk (6/10) depending on market conditions",
        "capital_requirements": "Very high capital needs (8/10) for property acquisition and development",
        "geographic_dependency": "High dependency (8/10) as real estate is inherently location-specific",
        "knowledge_half_life": "Long knowledge half-life (8/10) as fundamentals of real estate remain stable"
      }
    },
    {
      "id": "crypto_web3_venture",
      "name": "Crypto/Web3 Ventures",
      "category": "Finance & Investment",
      "description": "Develop projects in blockchain, DeFi, or web3 ecosystems",
      "target_customers": "Crypto users, investors, enterprises adopting blockchain",
      "success_examples": ["Early Ethereum contributors", "DeFi protocol founders"],
      "key_skills": ["Blockchain Development", "Cryptography", "Tokenomics", "Community Building"],
      "metrics": {
        "risk_level": {"value": 9, "range": [8, 10]},
        "capital_requirements": {"value": 4, "range": [3, 5]},
        "technical_specialization": {"value": 8, "range": [7, 9]},
        "network_dependency": {"value": 7, "range": [6, 8]},
        "scalability": {"value": 9, "range": [8, 10]},
        "control": {"value": 7, "range": [6, 8]},
        "geographic_dependency": {"value": 3, "range": [2, 4]},
        "skill_transfer": {"value": 6, "range": [5, 7]},
        "time_to_return": {"value": 3, "range": [2, 4]},
        "success_probability": {"value": 3, "range": [2, 4]},
        "optionality": {"value": 6, "range": [5, 7]},
        "terminal_value": {"value": 10, "range": [9, 10]},
        "expected_value_10yr": {"value": 6, "range": [5, 7]},
        "competition": {"value": 8, "range": [7, 9]},
        "social_impact": {"value": 6, "range": [5, 7]},
        "reversibility": {"value": 7, "range": [6, 8]},
        "team_dependency": {"value": 6, "range": [5, 7]},
        "regulatory_barriers": {"value": 6, "range": [5, 7]},
        "knowledge_half_life": {"value": 3, "range": [2, 4]}
      },
      "rationale": {
        "risk_level": "Very high risk (9/10) with extreme volatility and regulatory uncertainty",
        "time_to_return": "Potentially rapid returns (3/10) during bull markets with quick liquidity events",
        "success_probability": "Low probability (3/10) given high failure rates in crypto projects",
        "terminal_value": "Unlimited ceiling (10/10) with examples of billion-dollar protocols created by small teams"
      }
    },
    {
      "id": "research_commercialization",
      "name": "Research Commercialization",
      "category": "Materials & Energy",
      "description": "Develop patentable technology from research and license IP or create spinout",
      "target_customers": "Industrial firms, manufacturers, technology companies",
      "success_examples": ["University spinouts", "Research lab commercialization"],
      "key_skills": ["Scientific Research", "Intellectual Property", "Business Development", "Grant Writing"],
      "metrics": {
        "risk_level": {"value": 7, "range": [6, 8]},
        "capital_requirements": {"value": 7, "range": [6, 8]},
        "technical_specialization": {"value": 9, "range": [8, 10]},
        "network_dependency": {"value": 8, "range": [7, 9]},
        "scalability": {"value": 7, "range": [6, 8]},
        "control": {"value": 7, "range": [6, 8]},
        "geographic_dependency": {"value": 5, "range": [4, 6]},
        "skill_transfer": {"value": 7, "range": [6, 8]},
        "time_to_return": {"value": 7, "range": [6, 8]},
        "success_probability": {"value": 4, "range": [3, 5]},
        "optionality": {"value": 6, "range": [5, 7]},
        "terminal_value": {"value": 9, "range": [8, 10]},
        "expected_value_10yr": {"value": 6, "range": [5, 7]},
        "competition": {"value": 6, "range": [5, 7]},
        "social_impact": {"value": 8, "range": [7, 9]},
        "reversibility": {"value": 6, "range": [5, 7]},
        "team_dependency": {"value": 7, "range": [6, 8]},
        "regulatory_barriers": {"value": 7, "range": [6, 8]},
        "knowledge_half_life": {"value": 7, "range": [6, 8]}
      },
      "rationale": {
        "risk_level": "High risk (7/10) with long development cycles and commercialization challenges",
        "technical_specialization": "Very high specialization (9/10) requiring domain expertise and research background",
        "time_to_return": "Long timeline (7/10) with extended R&D and commercialization phases",
        "social_impact": "High potential impact (8/10) through breakthrough technologies addressing significant problems"
      }
    },
    {
      "id": "ai_model_dataset_development",
      "name": "AI Model/Dataset Development",
      "category": "Tech & Software",
      "description": "Create specialized AI models or datasets for licensing to enterprises",
      "target_customers": "Tech companies, AI startups, enterprise AI adopters",
      "success_examples": ["Hugging Face", "Scale AI", "Anthropic"],
      "key_skills": ["Machine Learning", "Data Science", "Domain Expertise", "MLOps"],
      "metrics": {
        "risk_level": {"value": 6, "range": [5, 7]},
        "capital_requirements": {"value": 5, "range": [4, 6]},
        "technical_specialization": {"value": 9, "range": [8, 10]},
        "network_dependency": {"value": 7, "range": [6, 8]},
        "scalability": {"value": 8, "range": [7, 9]},
        "control": {"value": 8, "range": [7, 9]},
        "geographic_dependency": {"value": 4, "range": [3, 5]},
        "skill_transfer": {"value": 8, "range": [7, 9]},
        "time_to_return": {"value": 5, "range": [4, 6]},
        "success_probability": {"value": 5, "range": [4, 6]},
        "optionality": {"value": 7, "range": [6, 8]},
        "terminal_value": {"value": 9, "range": [8, 10]},
        "expected_value_10yr": {"value": 7, "range": [6, 8]},
        "competition": {"value": 7, "range": [6, 8]},
        "social_impact": {"value": 7, "range": [6, 8]},
        "reversibility": {"value": 7, "range": [6, 8]},
        "team_dependency": {"value": 7, "range": [6, 8]},
        "regulatory_barriers": {"value": 4, "range": [3, 5]},
        "knowledge_half_life": {"value": 4, "range": [3, 5]}
      },
      "rationale": {
        "risk_level": "Moderate risk (6/10) with established market demand but technical challenges",
        "technical_specialization": "Very high specialization (9/10) requiring cutting-edge AI expertise",
        "scalability": "Strong scalability (8/10) with ability to deploy models and datasets widely",
        "knowledge_half_life": "Short half-life (4/10) with rapid evolution of AI techniques and models"
      }
    },
    {
      "id": "youtube_creator",
      "name": "YouTube Creator/Influencer",
      "category": "Content & Media",
      "description": "Build large audience through specialized content and monetize through multiple streams",
      "target_customers": "Viewers interested in specific topics, brands seeking promotion",
      "success_examples": ["MKBHD", "Mark Rober", "MrBeast"],
      "key_skills": ["Content Creation", "Video Production", "Personal Branding", "Audience Building"],
      "metrics": {
        "risk_level": {"value": 7, "range": [6, 8]},
        "capital_requirements": {"value": 3, "range": [2, 4]},
        "technical_specialization": {"value": 5, "range": [4, 6]},
        "network_dependency": {"value": 6, "range": [5, 7]},
        "scalability": {"value": 7, "range": [6, 8]},
        "control": {"value": 9, "range": [8, 10]},
        "geographic_dependency": {"value": 2, "range": [1, 3]},
        "skill_transfer": {"value": 6, "range": [5, 7]},
        "time_to_return": {"value": 5, "range": [4, 6]},
        "success_probability": {"value": 3, "range": [2, 4]},
        "optionality": {"value": 6, "range": [5, 7]},
        "terminal_value": {"value": 8, "range": [7, 9]},
        "expected_value_10yr": {"value": 5, "range": [4, 6]},
        "competition": {"value": 9, "range": [8, 10]},
        "social_impact": {"value": 6, "range": [5, 7]},
        "reversibility": {"value": 7, "range": [6, 8]},
        "team_dependency": {"value": 4, "range": [3, 5]},
        "regulatory_barriers": {"value": 2, "range": [1, 3]},
        "knowledge_half_life": {"value": 5, "range": [4, 6]}
      },
      "rationale": {
        "risk_level": "High risk (7/10) with platform dependency and audience unpredictability",
        "success_probability": "Low probability (3/10) with <1% of creators reaching significant income levels",
        "geographic_dependency": "Very low dependency (2/10) allowing remote operation from anywhere",
        "competition": "Extremely competitive (9/10) with millions of creators competing for audience attention"
      }
    },
    {
      "id": "online_course_creator",
      "name": "Online Course Creator/Educator",
      "category": "Education",
      "description": "Develop premium educational content in specialized domains",
      "target_customers": "Professionals seeking to improve skills, career changers",
      "success_examples": ["Andrew Ng's courses", "Zero To Mastery", "Ali Abdaal"],
      "key_skills": ["Domain Expertise", "Educational Design", "Content Creation", "Marketing"],
      "metrics": {
        "risk_level": {"value": 5, "range": [4, 6]},
        "capital_requirements": {"value": 3, "range": [2, 4]},
        "technical_specialization": {"value": 7, "range": [6, 8]},
        "network_dependency": {"value": 6, "range": [5, 7]},
        "scalability": {"value": 8, "range": [7, 9]},
        "control": {"value": 9, "range": [8, 10]},
        "geographic_dependency": {"value": 2, "range": [1, 3]},
        "skill_transfer": {"value": 7, "range": [6, 8]},
        "time_to_return": {"value": 4, "range": [3, 5]},
        "success_probability": {"value": 5, "range": [4, 6]},
        "optionality": {"value": 7, "range": [6, 8]},
        "terminal_value": {"value": 7, "range": [6, 8]},
        "expected_value_10yr": {"value": 6, "range": [5, 7]},
        "competition": {"value": 8, "range": [7, 9]},
        "social_impact": {"value": 7, "range": [6, 8]},
        "reversibility": {"value": 7, "range": [6, 8]},
        "team_dependency": {"value": 3, "range": [2, 4]},
        "regulatory_barriers": {"value": 2, "range": [1, 3]},
        "knowledge_half_life": {"value": 4, "range": [3, 5]}
      },
      "rationale": {
        "risk_level": "Moderate risk (5/10) with established market for quality educational content",
        "scalability": "Strong scalability (8/10) with courses serving unlimited students once created",
        "geographic_dependency": "Very low dependency (2/10) allowing operation from anywhere",
        "team_dependency": "Low dependency (3/10) with ability to operate as solo creator or small team"
      }
    },
    {
      "id": "ai_3d_generative_architect",
      "name": "AI 3D Generative Design Architect",
      "category": "3D & Manufacturing",
      "description": "Develop expertise in AI-driven 3D design and generative architecture",
      "target_customers": "Design firms, architectural studios, manufacturing companies",
      "success_examples": ["Leaders in computational design at top architectural firms"],
      "key_skills": ["3D Modeling", "Computational Design", "Machine Learning", "Design Principles"],
      "metrics": {
        "risk_level": {"value": 5, "range": [4, 6]},
        "capital_requirements": {"value": 3, "range": [2, 4]},
        "technical_specialization": {"value": 9, "range": [8, 10]},
        "network_dependency": {"value": 7, "range": [6, 8]},
        "scalability": {"value": 6, "range": [5, 7]},
        "control": {"value": 6, "range": [5, 7]},
        "geographic_dependency": {"value": 5, "range": [4, 6]},
        "skill_transfer": {"value": 7, "range": [6, 8]},
        "time_to_return": {"value": 5, "range": [4, 6]},
        "success_probability": {"value": 5, "range": [4, 6]},
        "optionality": {"value": 7, "range": [6, 8]},
        "terminal_value": {"value": 7, "range": [6, 8]},
        "expected_value_10yr": {"value": 6, "range": [5, 7]},
        "competition": {"value": 6, "range": [5, 7]},
        "social_impact": {"value": 7, "range": [6, 8]},
        "reversibility": {"value": 7, "range": [6, 8]},
        "team_dependency": {"value": 6, "range": [5, 7]},
        "regulatory_barriers": {"value": 4, "range": [3, 5]},
        "knowledge_half_life": {"value": 5, "range": [4, 6]}
      },
      "rationale": {
        "risk_level": "Moderate risk (5/10) with emerging but growing field",
        "technical_specialization": "Very high specialization (9/10) requiring rare combination of design and AI skills",
        "competition": "Moderate competition (6/10) due to specialized skill requirements creating barrier to entry",
        "social_impact": "High potential impact (7/10) through more efficient and sustainable design approaches"
      }
    },
    {
      "id": "consumer_hardware_startup",
      "name": "Consumer Hardware Startup",
      "category": "3D & Manufacturing",
      "description": "Create innovative physical products for consumer markets",
      "target_customers": "General consumers or specific market segments",
      "success_examples": ["Ring", "Peloton", "Nest"],
      "key_skills": ["Hardware Design", "Manufacturing", "Supply Chain Management", "Product Marketing"],
      "metrics": {
        "risk_level": {"value": 8, "range": [7, 9]},
        "capital_requirements": {"value": 8, "range": [7, 9]},
        "technical_specialization": {"value": 7, "range": [6, 8]},
        "network_dependency": {"value": 8, "range": [7, 9]},
        "scalability": {"value": 7, "range": [6, 8]},
        "control": {"value": 7, "range": [6, 8]},
        "geographic_dependency": {"value": 6, "range": [5, 7]},
        "skill_transfer": {"value": 7, "range": [6, 8]},
        "time_to_return": {"value": 6, "range": [5, 7]},
        "success_probability": {"value": 3, "range": [2, 4]},
        "optionality": {"value": 6, "range": [5, 7]},
        "terminal_value": {"value": 9, "range": [8, 10]},
        "expected_value_10yr": {"value": 6, "range": [5, 7]},
        "competition": {"value": 8, "range": [7, 9]},
        "social_impact": {"value": 6, "range": [5, 7]},
        "reversibility": {"value": 5, "range": [4, 6]},
        "team_dependency": {"value": 8, "range": [7, 9]},
        "regulatory_barriers": {"value": 6, "range": [5, 7]},
        "knowledge_half_life": {"value": 6, "range": [5, 7]}
      },
      "rationale": {
        "risk_level": "High risk (8/10) with manufacturing, supply chain, and market acceptance challenges",
        "capital_requirements": "Very high capital needs (8/10) for prototyping, tooling, and inventory",
        "success_probability": "Low probability (3/10) with high failure rate for hardware startups",
        "terminal_value": "Very high ceiling (9/10) for successful consumer hardware companies"
      }
    },
    {
      "id": "robotics_automation_company",
      "name": "Robotics/Automation Company",
      "category": "3D & Manufacturing",
      "description": "Develop robotic systems for industrial or commercial applications",
      "target_customers": "Manufacturing companies, warehouses, healthcare facilities",
      "success_examples": ["Boston Dynamics", "Fetch Robotics", "Locus Robotics"],
      "key_skills": ["Robotics Engineering", "Computer Vision", "Mechanical Design", "Systems Integration"],
      "metrics": {
        "risk_level": {"value": 7, "range": [6, 8]},
        "capital_requirements": {"value": 9, "range": [8, 10]},
        "technical_specialization": {"value": 9, "range": [8, 10]},
        "network_dependency": {"value": 7, "range": [6, 8]},
        "scalability": {"value": 7, "range": [6, 8]},
        "control": {"value": 8, "range": [7, 9]},
        "geographic_dependency": {"value": 6, "range": [5, 7]},
        "skill_transfer": {"value": 8, "range": [7, 9]},
        "time_to_return": {"value": 7, "range": [6, 8]},
        "success_probability": {"value": 4, "range": [3, 5]},
        "optionality": {"value": 7, "range": [6, 8]},
        "terminal_value": {"value": 9, "range": [8, 10]},
        "expected_value_10yr": {"value": 7, "range": [6, 8]},
        "competition": {"value": 7, "range": [6, 8]},
        "social_impact": {"value": 8, "range": [7, 9]},
        "reversibility": {"value": 6, "range": [5, 7]},
        "team_dependency": {"value": 8, "range": [7, 9]},
        "regulatory_barriers": {"value": 5, "range": [4, 6]},
        "knowledge_half_life": {"value": 7, "range": [6, 8]}
      },
      "rationale": {
        "risk_level": "High risk (7/10) with complex engineering and market adoption challenges",
        "capital_requirements": "Extremely high capital needs (9/10) for development, testing, and production",
        "technical_specialization": "Very high specialization (9/10) requiring multidisciplinary expertise",
        "time_to_return": "Long timeline (7/10) with extended development and sales cycles"
      }
    },
    {
      "id": "renewable_energy_development",
      "name": "Renewable Energy Development",
      "category": "Materials & Energy",
      "description": "Develop renewable energy projects or enabling technologies",
      "target_customers": "Utilities, businesses, governments, consumers",
      "success_examples": ["Solar development firms", "Wind farm developers", "Energy storage startups"],
      "key_skills": ["Energy Systems", "Project Development", "Regulatory Navigation", "Financial Modeling"],
      "metrics": {
        "risk_level": {"value": 6, "range": [5, 7]},
        "capital_requirements": {"value": 9, "range": [8, 10]},
        "technical_specialization": {"value": 7, "range": [6, 8]},
        "network_dependency": {"value": 8, "range": [7, 9]},
        "scalability": {"value": 7, "range": [6, 8]},
        "control": {"value": 7, "range": [6, 8]},
        "geographic_dependency": {"value": 7, "range": [6, 8]},
        "skill_transfer": {"value": 7, "range": [6, 8]},
        "time_to_return": {"value": 7, "range": [6, 8]},
        "success_probability": {"value": 5, "range": [4, 6]},
        "optionality": {"value": 6, "range": [5, 7]},
        "terminal_value": {"value": 8, "range": [7, 9]},
        "expected_value_10yr": {"value": 7, "range": [6, 8]},
        "competition": {"value": 7, "range": [6, 8]},
        "social_impact": {"value": 9, "range": [8, 10]},
        "reversibility": {"value": 5, "range": [4, 6]},
        "team_dependency": {"value": 7, "range": [6, 8]},
        "regulatory_barriers": {"value": 8, "range": [7, 9]},
        "knowledge_half_life": {"value": 7, "range": [6, 8]}
      },
      "rationale": {
        "risk_level": "Moderate risk (6/10) with policy support but project execution challenges",
        "capital_requirements": "Extremely high capital needs (9/10) for project development and construction",
        "regulatory_barriers": "High barriers (8/10) requiring navigation of complex energy regulations",
        "social_impact": "Very high impact (9/10) through clean energy transition and climate mitigation"
      }
    },
    {
      "id": "d2c_brand_development",
      "name": "D2C Brand Development",
      "category": "Retail & Consumer",
      "description": "Create direct-to-consumer brand with premium positioning and margins",
      "target_customers": "Consumers seeking quality products in specific categories",
      "success_examples": ["Warby Parker", "Allbirds", "Dollar Shave Club"],
      "key_skills": ["Brand Development", "E-commerce", "Supply Chain Management", "Digital Marketing"],
      "metrics": {
        "risk_level": {"value": 7, "range": [6, 8]},
        "capital_requirements": {"value": 6, "range": [5, 7]},
        "technical_specialization": {"value": 5, "range": [4, 6]},
        "network_dependency": {"value": 6, "range": [5, 7]},
        "scalability": {"value": 7, "range": [6, 8]},
        "control": {"value": 8, "range": [7, 9]},
        "geographic_dependency": {"value": 4, "range": [3, 5]},
        "skill_transfer": {"value": 7, "range": [6, 8]},
        "time_to_return": {"value": 5, "range": [4, 6]},
        "success_probability": {"value": 4, "range": [3, 5]},
        "optionality": {"value": 6, "range": [5, 7]},
        "terminal_value": {"value": 8, "range": [7, 9]},
        "expected_value_10yr": {"value": 6, "range": [5, 7]},
        "competition": {"value": 8, "range": [7, 9]},
        "social_impact": {"value": 5, "range": [4, 6]},
        "reversibility": {"value": 6, "range": [5, 7]},
        "team_dependency": {"value": 6, "range": [5, 7]},
        "regulatory_barriers": {"value": 4, "range": [3, 5]},
        "knowledge_half_life": {"value": 6, "range": [5, 7]}
      },
      "rationale": {
        "risk_level": "High risk (7/10) with challenging customer acquisition economics",
        "technical_specialization": "Moderate specialization (5/10) focusing more on brand and marketing than technical complexity",
        "competition": "High competition (8/10) with low barriers to entry and many players",
        "terminal_value": "High ceiling (8/10) with successful D2C brands achieving significant exits"
      }
    },
    {
      "id": "legal_tech_founder",
      "name": "Legal Tech Founder/Entrepreneur",
      "category": "Tech & Software",
      "description": "Create software solutions for legal industry pain points",
      "target_customers": "Law firms, corporate legal departments, individual attorneys",
      "success_examples": ["Clio", "DISCO", "HelloSign"],
      "key_skills": ["Legal Knowledge", "Software Development", "UX Design", "Sales to Legal Market"],
      "metrics": {
        "risk_level": {"value": 6, "range": [5, 7]},
        "capital_requirements": {"value": 5, "range": [4, 6]},
        "technical_specialization": {"value": 6, "range": [5, 7]},
        "network_dependency": {"value": 8, "range": [7, 9]},
        "scalability": {"value": 8, "range": [7, 9]},
        "control": {"value": 8, "range": [7, 9]},
        "geographic_dependency": {"value": 5, "range": [4, 6]},
        "skill_transfer": {"value": 7, "range": [6, 8]},
        "time_to_return": {"value": 6, "range": [5, 7]},
        "success_probability": {"value": 5, "range": [4, 6]},
        "optionality": {"value": 6, "range": [5, 7]},
        "terminal_value": {"value": 8, "range": [7, 9]},
        "expected_value_10yr": {"value": 7, "range": [6, 8]},
        "competition": {"value": 7, "range": [6, 8]},
        "social_impact": {"value": 6, "range": [5, 7]},
        "reversibility": {"value": 6, "range": [5, 7]},
        "team_dependency": {"value": 6, "range": [5, 7]},
        "regulatory_barriers": {"value": 5, "range": [4, 6]},
        "knowledge_half_life": {"value": 6, "range": [5, 7]}
      },
      "rationale": {
        "risk_level": "Moderate risk (6/10) with conservative but stable legal market",
        "network_dependency": "High dependency (8/10) as access to legal decision-makers is critical",
        "scalability": "Strong scalability (8/10) with software economics in large professional services market",
        "expected_value_10yr": "Good expected value (7/10) with several notable exits in legal tech space"
      }
    },
    {
      "id": "litigation_boutique_founder",
      "name": "Litigation Boutique Founder",
      "category": "Traditional Professions",
      "description": "Establish specialized law firm focused on high-value litigation",
      "target_customers": "Businesses and individuals with significant legal disputes",
      "success_examples": ["Susman Godfrey", "Keker & Van Nest", "Quinn Emanuel"],
      "key_skills": ["Legal Expertise", "Trial Skills", "Business Development", "Team Management"],
      "metrics": {
        "risk_level": {"value": 5, "range": [4, 6]},
        "capital_requirements": {"value": 4, "range": [3, 5]},
        "technical_specialization": {"value": 8, "range": [7, 9]},
        "network_dependency": {"value": 9, "range": [8, 10]},
        "scalability": {"value": 5, "range": [4, 6]},
        "control": {"value": 9, "range": [8, 10]},
        "geographic_dependency": {"value": 7, "range": [6, 8]},
        "skill_transfer": {"value": 5, "range": [4, 6]},
        "time_to_return": {"value": 5, "range": [4, 6]},
        "success_probability": {"value": 5, "range": [4, 6]},
        "optionality": {"value": 5, "range": [4, 6]},
        "terminal_value": {"value": 7, "range": [6, 8]},
        "expected_value_10yr": {"value": 6, "range": [5, 7]},
        "competition": {"value": 7, "range": [6, 8]},
        "social_impact": {"value": 5, "range": [4, 6]},
        "reversibility": {"value": 6, "range": [5, 7]},
        "team_dependency": {"value": 6, "range": [5, 7]},
        "regulatory_barriers": {"value": 7, "range": [6, 8]},
        "knowledge_half_life": {"value": 7, "range": [6, 8]}
      },
      "rationale": {
        "risk_level": "Moderate risk (5/10) with established business model and clear revenue path",
        "network_dependency": "Very high dependency (9/10) as client relationships drive business",
        "control": "Very high control (9/10) with partnership structure providing autonomy",
        "scalability": "Limited scalability (5/10) constrained by partner time and expertise"
      }
    },
    {
      "id": "hedge_fund_pm",
      "name": "Hedge Fund Portfolio Manager",
      "category": "Finance & Investment",
      "description": "Manage investment portfolio at established hedge fund",
      "target_customers": "Institutional investors, high-net-worth individuals",
      "success_examples": ["Top portfolio managers at major funds"],
      "key_skills": ["Financial Analysis", "Strategy Development", "Risk Management", "Investor Relations"],
      "metrics": {
        "risk_level": {"value": 4, "range": [3, 5]},
        "capital_requirements": {"value": 3, "range": [2, 4]},
        "technical_specialization": {"value": 8, "range": [7, 9]},
        "network_dependency": {"value": 8, "range": [7, 9]},
        "scalability": {"value": 8, "range": [7, 9]},
        "control": {"value": 6, "range": [5, 7]},
        "geographic_dependency": {"value": 7, "range": [6, 8]},
        "skill_transfer": {"value": 7, "range": [6, 8]},
        "time_to_return": {"value": 6, "range": [5, 7]},
        "success_probability": {"value": 5, "range": [4, 6]},
        "optionality": {"value": 7, "range": [6, 8]},
        "terminal_value": {"value": 8, "range": [7, 9]},
        "expected_value_10yr": {"value": 7, "range": [6, 8]},
        "competition": {"value": 9, "range": [8, 10]},
        "social_impact": {"value": 4, "range": [3, 5]},
        "reversibility": {"value": 7, "range": [6, 8]},
        "team_dependency": {"value": 7, "range": [6, 8]},
        "regulatory_barriers": {"value": 6, "range": [5, 7]},
        "knowledge_half_life": {"value": 6, "range": [5, 7]}
      },
      "rationale": {
        "risk_level": "Moderate risk (4/10) with established career path but performance volatility",
        "competition": "Extremely competitive (9/10) for top portfolio manager positions",
        "scalability": "Good scalability (8/10) with ability to manage increasing AUM with similar effort",
        "terminal_value": "High ceiling (8/10) with top performers earning $10M+ annually through performance fees"
      }
    },
    {
      "id": "fortune_500_gc",
      "name": "Fortune 500 General Counsel",
      "category": "Traditional Professions",
      "description": "Rise to top legal position at major corporation",
      "target_customers": "N/A (internal leadership role)",
      "success_examples": ["GCs at major tech and financial companies"],
      "key_skills": ["Legal Expertise", "Corporate Strategy", "Leadership", "Risk Management"],
      "metrics": {
        "risk_level": {"value": 3, "range": [2, 4]},
        "capital_requirements": {"value": 2, "range": [1, 3]},
        "technical_specialization": {"value": 7, "range": [6, 8]},
        "network_dependency": {"value": 8, "range": [7, 9]},
        "scalability": {"value": 4, "range": [3, 5]},
        "control": {"value": 5, "range": [4, 6]},
        "geographic_dependency": {"value": 7, "range": [6, 8]},
        "skill_transfer": {"value": 6, "range": [5, 7]},
        "time_to_return": {"value": 8, "range": [7, 9]},
        "success_probability": {"value": 4, "range": [3, 5]},
        "optionality": {"value": 6, "range": [5, 7]},
        "terminal_value": {"value": 6, "range": [5, 7]},
        "expected_value_10yr": {"value": 5, "range": [4, 6]},
        "competition": {"value": 9, "range": [8, 10]},
        "social_impact": {"value": 5, "range": [4, 6]},
        "reversibility": {"value": 7, "range": [6, 8]},
        "team_dependency": {"value": 7, "range": [6, 8]},
        "regulatory_barriers": {"value": 6, "range": [5, 7]},
        "knowledge_half_life": {"value": 7, "range": [6, 8]}
      },
      "rationale": {
        "risk_level": "Low risk (3/10) with established career path",
        "time_to_return": "Long timeline (8/10) requiring 15-20+ years to reach GC level",
        "competition": "Extremely competitive (9/10) for limited top positions",
        "terminal_value": "Good ceiling (6/10) with total compensation of $1-5M for Fortune 500 GCs"
      }
    },
    {
      "id": "health_system_executive",
      "name": "Healthcare System Executive",
      "category": "Health & Wellness",
      "description": "Rise to leadership in major health system or hospital network",
      "target_customers": "N/A (internal leadership role)",
      "success_examples": ["CEOs of major health systems", "Hospital group executives"],
      "key_skills": ["Healthcare Administration", "Financial Management", "Regulatory Compliance", "Operational Efficiency"],
      "metrics": {
        "risk_level": {"value": 2, "range": [1, 3]},
        "capital_requirements": {"value": 2, "range": [1, 3]},
        "technical_specialization": {"value": 7, "range": [6, 8]},
        "network_dependency": {"value": 8, "range": [7, 9]},
        "scalability": {"value": 4, "range": [3, 5]},
        "control": {"value": 5, "range": [4, 6]},
        "geographic_dependency": {"value": 6, "range": [5, 7]},
        "skill_transfer": {"value": 6, "range": [5, 7]},
        "time_to_return": {"value": 8, "range": [7, 9]},
        "success_probability": {"value": 5, "range": [4, 6]},
        "optionality": {"value": 5, "range": [4, 6]},
        "terminal_value": {"value": 6, "range": [5, 7]},
        "expected_value_10yr": {"value": 5, "range": [4, 6]},
        "competition": {"value": 8, "range": [7, 9]},
        "social_impact": {"value": 7, "range": [6, 8]},
        "reversibility": {"value": 6, "range": [5, 7]},
        "team_dependency": {"value": 8, "range": [7, 9]},
        "regulatory_barriers": {"value": 8, "range": [7, 9]},
        "knowledge_half_life": {"value": 7, "range": [6, 8]}
      },
      "rationale": {
        "risk_level": "Very low risk (2/10) with stable healthcare sector",
        "regulatory_barriers": "High barriers (8/10) with complex healthcare compliance requirements",
        "social_impact": "High impact potential (7/10) through healthcare system improvements",
        "time_to_return": "Long timeline (8/10) requiring 15-20+ years to reach executive level"
      }
    }
  ]
}